DROP TABLE IF EXISTS dm.dm_f101_round_f_v2;
CREATE TABLE dm.dm_f101_round_f_v2(
	FROM_DATE DATE,
	TO_DATE DATE,
	CHAPTER CHAR(1),
	LEDGER_ACCOUNT CHAR(5),
	CHARACTERISTIC CHAR(1),
	BALANCE_IN_RUB NUMERIC(23,8),
	BALANCE_IN_VAL NUMERIC(23,8),
	BALANCE_IN_TOTAL NUMERIC(23,8),
	TURN_DEB_RUB NUMERIC(23,8),
	TURN_DEB_VAL NUMERIC(23,8),
	TURN_DEB_TOTAL NUMERIC(23,8),
	TURN_CRE_RUB NUMERIC(23,8),
	TURN_CRE_VAL NUMERIC(23,8),
	TURN_CRE_TOTAL NUMERIC(23,8),
	BALANCE_OUT_RUB NUMERIC(23,8),
	BALANCE_OUT_VAL NUMERIC(23,8),
	BALANCE_OUT_TOTAL NUMERIC(23,8),
	CONSTRAINT PK_LEDGER_ACCOUNT_V2 PRIMARY KEY (LEDGER_ACCOUNT, FROM_DATE)
);

INSERT INTO dm.dm_f101_round_f_v2
SELECT * FROM dm.dm_f101_round_f;



